<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QN1NF34" ignored="0" name="Failure Test" tests="1" failures="1" timestamp="2020-06-05T10:26:44 CEST" time="0.008" errors="0">
  <testcase name="doLogin" time="0.002" classname="TestCases.TestFailure">
    <failure type="java.lang.AssertionError" message="Failing the login test">
      <![CDATA[java.lang.AssertionError: Failing the login test
at TestCases.TestFailure.doLogin(TestFailure.java:11)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
</testsuite> <!-- Failure Test -->
